-- Fuentes confiables y correos favoritos, editables desde la sección Configuración.
create table fuentes_confiables (
  dominio    text primary key check (dominio = lower(dominio) and length(dominio) between 4 and 100),
  creado_en  timestamptz not null default now()
);

create table correos_favoritos (
  id         bigint generated always as identity primary key,
  email      text not null unique check (email = lower(email) and length(email) <= 254),
  nombre     text check (length(nombre) <= 100),
  creado_en  timestamptz not null default now()
);

alter table fuentes_confiables enable row level security;
alter table correos_favoritos  enable row level security;

-- Lista inicial = config/fuentes.json
insert into fuentes_confiables (dominio) values
  ('kantar.com'),
  ('nielsen.com'),
  ('ipsos.com'),
  ('mintel.com'),
  ('euromonitor.com'),
  ('statista.com'),
  ('emarketer.com'),
  ('warc.com'),
  ('mckinsey.com'),
  ('deloitte.com'),
  ('gartner.com'),
  ('forrester.com'),
  ('bcg.com'),
  ('bain.com'),
  ('pwc.com'),
  ('accenture.com'),
  ('hbr.org'),
  ('thinkwithgoogle.com'),
  ('business.google.com'),
  ('meta.com'),
  ('business.linkedin.com'),
  ('iab.com'),
  ('iabeurope.eu'),
  ('wfanet.org'),
  ('ama.org'),
  ('adweek.com'),
  ('adage.com'),
  ('marketingweek.com'),
  ('thedrum.com'),
  ('campaignlive.com'),
  ('canneslions.com'),
  ('eventmarketer.com'),
  ('kantaribopemedia.com'),
  ('nielseniq.com'),
  ('datareportal.com'),
  ('wearesocial.com'),
  ('pewresearch.org'),
  ('capgemini.com'),
  ('kearney.com'),
  ('ey.com'),
  ('kpmg.com'),
  ('weforum.org'),
  ('oecd.org'),
  ('cepal.org'),
  ('ana.net'),
  ('ipa.co.uk'),
  ('effie.org'),
  ('contentmarketinginstitute.com'),
  ('socialmediatoday.com'),
  ('marketingdive.com'),
  ('bizbash.com'),
  ('mpi.org'),
  ('iaee.com'),
  ('promomarketing.com'),
  ('fastcompany.mx'),
  ('marketingdirecto.com'),
  ('merca20.com'),
  ('reasonwhy.es'),
  ('puromarketing.com'),
  ('marketingnews.es'),
  ('elpublicista.es'),
  ('dineroenimagen.com'),
  ('mercadeo.com'),
  ('revistapym.com.co'),
  ('portafolio.co'),
  ('anda.org.co'),
  ('ccce.org.co'),
  ('iabcolombia.com'),
  ('iabspain.es'),
  ('iabmexico.com');
